### PR TITLE
docs: fix code highlight in README

### PR DESCRIPTION
**Pull request by sobolevn**
After:

Снимок экрана 2024-08-26 в 15 30 30

### CODE REVIEW

**Comment by kszucs** [comment]
Sorry for the late response, I was AFK.

**Review by kszucs — APPROVED** [review]
Thanks @sobolevn!

Let me know if you have any ideas for the project!

**Comment by kszucs** [comment]
@sobolevn you might be interested in typehint based singledispatching:

```py
    @classmethod
    def visit(cls, op: ops.Array, exprs):
        return cls.rowwise(lambda row: np.array(row, dtype=object), exprs)

    @classmethod
    def visit(cls, op: ops.StructColumn, names, values):
        return cls.rowwise(lambda row: dict(zip(names, row)), values)

    @classmethod
    def visit(cls, op: ops.ArrayConcat, arg):
        return cls.rowwise(lambda row: np.concatenate(row.values), arg)

    @classmethod
    def visit(cls, op: ops.Unnest, arg):
        arg = cls.asseries(arg)
        mask = arg.map(lambda v: bool(len(v)), na_action="ignore")
        return arg[mask].explode()
```

from https://github.com/ibis-project/ibis/blob/be455f2768deef8abf4f4a1e615aeafc61f4020e/ibis/backends/pandas/executor.py#L226-L242

**Comment by sobolevn** [comment]
@kszucs I did this once in https://github.com/dry-python/classes :)
But, it was rather hard to maintain.

**Comment by sobolevn** [comment]
Sure, feel free to ping me for advice / reviews :)

**Pull request merged**
